robot_hardware:
  - sample_b3m_hardware

sample_b3m_hardware:
  type: b3m_hw_interface/B3MHwInterface
  port: /dev/ttyUSB0
  baudrate: 1500000
  joints:
    joint1:
      servo_id: 1
      gear_ratio: 1.0
      reverse: false
    joint2:
      servo_id: 2
      gear_ratio: 2.0
      reverse: true
