robot_hardware:
  - sample_b3m_hardware

sample_b3m_hardware:
  type: b3m_hw_interface/B3mHwInterface
  port: /dev/ttyUSB0
  baudrate: 1000000
  joints:
    joint1:
      servo_id: 1
      gear_ratio: 1.0
      reverse: false
    joint2:
      servo_id: 2
      gear_ratio: 2.0
      reverse: true

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

joint1_position_controller:
  type: position_controllers/JointPositionController
  publish_rate: 100
  base_frame_id: base_link
  joint: joint1

joint2_position_controller:
  type: position_controllers/JointPositionController
  publish_rate: 100
  base_frame_id: base_link
  joint: joint2
